- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: install
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - nmap-ncat
        - bind-utils         