--- #Error handling
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: install
      yum:
        name: nmap
        state: latest
      ignore_errors: yes
    - name: utility
      command: /home/cloud_user/error/file.sh write
      register: cmd_output
      changed_when: "'changed' in cmd_output.stdout"
      failed_when: "'failed' in cmd_output.stdout"
    - debug:
        msg:
          - "{{ cmd_output }}"